// eslint-disable-next-line import/prefer-default-export
export const mockArticles = [{
  'uri': 'nyt://article/7d22b056-2e3b-5778-b1c4-526f651778b9',
  'url': 'https://www.nytimes.com/2022/03/22/magazine/ethicist-teenage-sex-parenting.html',
  'id': 100000008260402,
  'asset_id': 100000008260402,
  'source': 'New York Times',
  'published_date': '2022-03-22',
  'updated': '2024-04-25 13:35:02',
  'section': 'Magazine',
  'subsection': '',
  'nytdsection': 'magazine',
  'adx_keywords': 'Ethics (Personal);Content Type: Service',
  'column': null,
  'byline': 'By Kwame Anthony Appiah',
  'type': 'Article',
  'title': 'My Daughter Is Having Sex With Her Best Friend. Must I Tell Her Mom?',
  'abstract': 'The magazine\'s Ethicist columnist on whether to keep your teenager’s.',
  'des_facet': [
    'Ethics (Personal)',
    'Content Type: Service',
  ],
  'org_facet': [],
  'per_facet': [],
  'geo_facet': [],
  'media': [
    {
      'type': 'image',
      'subtype': 'photo',
      'caption': '',
      'copyright': 'Illustration by Tomi Um',
      'approved_for_syndication': 0,
      'media-metadata': [
        {
          'url': 'https://static01.nyt.com/images/magazine/27mag-ethicist/27mag-ethicist-thumbStandard.jpg',
          'format': 'Standard Thumbnail',
          'height': 75,
          'width': 75,
        },
        {
          'url': 'https://static01.nyt.com/images/magazine/27mag-ethicist/27mag-ethicist-mediumThreeByTwo210.jpg',
          'format': 'mediumThreeByTwo210',
          'height': 140,
          'width': 210,
        },
        {
          'url': 'https://static01.nyt.com/images/magazine/27mag-ethicist/27mag-ethicist-mediumThreeByTwo440.jpg',
          'format': 'mediumThreeByTwo440',
          'height': 293,
          'width': 440,
        },
      ],
    },
  ],
  'eta_id': 0,
}]
