export const GET_POPULAR_ARTICLES_REQUEST = 'GET_POPULAR_ARTICLES_REQUEST'
export const GET_POPULAR_ARTICLES_SUCCESS = 'GET_POPULAR_ARTICLES_SUCCESS'
export const GET_POPULAR_ARTICLES_FAILURE = 'GET_POPULAR_ARTICLES_FAILURE'
